username:

user:
#  bio:
#  email:
#  company:
#  location:
#  social_media:

repos:
#  sample-repo:
#    description:
#    language:    ""
#  sample-app:
#    html_url:
#    description:

exclude_repos:
#  - other-repo

skills:
#  language:

exclude_skills:
#  - other-language

history: false
others:  false

system:
  limit_of_auto_get: 12
  exclude_fork_repo: true
  sort_repos_by:     star

  titles:
#    repos:
#    repos_sub:
#    skills:
#    skills_sub:
#    history:
#    history_sub:
#    others:
#    others_sub:
